In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

###############################################################
# Construct a randomly initialized matrix:

x = torch.rand(5, 3)
print(x)

###############################################################
# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

###############################################################
# Construct a tensor directly from data:

x = torch.tensor([5.5, 3])
print(x)

tensor([[-1.1048e-16,  4.5646e-41, -1.1048e-16],
        [ 4.5646e-41,  3.0357e+32,  1.3563e-19],
        [ 1.1290e+27,  1.8037e+28,  2.6454e+20],
        [ 2.8492e+20,  5.0850e+31,  1.9421e+31],
        [ 3.6002e+27,  8.8674e-04,  6.2717e+22]])
tensor([[0.5726, 0.6071, 0.8760],
        [0.6099, 0.5070, 0.9440],
        [0.0398, 0.5501, 0.3911],
        [0.4772, 0.3841, 0.6563],
        [0.7527, 0.8537, 0.6704]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


In [5]:
print(x.abs())

tensor([5.5000, 3.0000])


In [6]:

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)          

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0046, -0.6197,  0.4933],
        [-0.4347, -0.1363, -1.0836],
        [ 0.4490, -0.4388,  0.6483],
        [-0.0542, -0.5115,  0.4337],
        [ 1.0112,  0.1185, -0.9061]])


In [7]:
print(x.size()) 

torch.Size([5, 3])


In [8]:
###############################################################
# Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

###############################################################
# If you have a one element tensor, use ``.item()`` to get the value as a
# Python number
x = torch.randn(1)
print(x)
print(x.item())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([1.0344])
1.0344314575195312


In [9]:

a = torch.ones(5)
print(a)

###############################################################
#

b = a.numpy()
print(b)

###############################################################
# See how the numpy array changed in value.

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [10]:
print (torch.cuda.is_available())

False
